package com.twitchsnitch.importer.opentender.enums;

/**
 BUYER ACTIVITY TYPE
 GENERAL_PUBLIC_SERVICES
 SOCIAL_PROTECTION
 EDUCATION
 HEALTH
 ENVIRONMENT
 PUBLIC_ORDER_AND_SAFETY
 HOUSING_AND_COMMUNITY_AMENITIES
 DEFENCE
 ECONOMIC_AND_FINANCIAL_AFFAIRS
 RECREATION_CULTURE_AND_RELIGION
 GAS_AND_HEAT_PRODUCTION
 GAS_AND_OIL_EXTRACTION
 COAL_AND_OTHER_EXTRACTION
 ELECTRICITY
 WATER
 POSTAL
 RAILWAY
 URBAN_TRANSPORT
 PORT
 AIRPORT
 OTHER
 */
public enum BuyerActivityType {
    GENERAL_PUBLIC_SERVICES, SOCIAL_PROTECTION, EDUCATION, HEALTH, ENVIRONMENT, PUBLIC_ORDER_AND_SAFETY, HOUSING_AND_COMMUNITY_AMENITIES,
    DEFENCE, ECONOMIC_AND_FINANCIAL_AFFAIRS, RECREATION_CULTURE_AND_RELIGION, GAS_AND_HEAT_PRODUCTION, GAS_AND_OIL_EXTRACTION, COAL_AND_OTHER_EXTRACTION,
    ELECTRICITY, WATER, POSTAL, RAILWAY, URBAN_TRANSPORT, PORT, AIRPORT, OTHER
}