package com.twitchsnitch.importer.opentender.enums;

/**
 DISQUALIFICATION REASON
 BIDDERS_COUNT_LIMIT
 QUALIFICATION_CRITERIA_NOT_MET
 EXCEPTIONALLY_LOW_PRICE
 INCOMPLETE_OR_UNACCEPTABLE_TENDER
 */
public enum DisqualificationReason {
    BIDDERS_COUNT_LIMIT, QUALIFICATION_CRITERIA_NOT_MET, EXCEPTIONALLY_LOW_PRICE, INCOMPLETE_OR_UNACCEPTABLE_TENDER
}