package com.twitchsnitch.importer.opentender.enums;

/**
 DOCUMENT TYPE	typology of full tender documentation (NOT announcement types)
 PROJECT_PLAN
 MARKET_RESEARCH
 SPECIFICATIONS
 QUALIFICATION_DOCUMENTS
 CALL_FOR_TENDERS
 ADDITIONAL_INFORMATION	enquiry for additional information
 CANDIDATES_NUMBER_LIMITATION_PROTOCOL
 QUALIFICATIONS_EVALUATION_PROTOCOL
 BIDDER_NEGOTIATION_PROTOCOL
 OWNERSHIP_STRUCTURE
 OBJECTION
 TENDER
 EVALUATION_COMITTEE_PROTOCOL
 TENDERS_EVALUATION_PROTOCOL
 BEST_TENDER_SELECTION_NOTICE
 CONTRACTOR_AGREEMENT
 AGREEMENT_AMENDMENT
 BUYER_REPORT
 BUYERS_GROUPING_AGREEMENT
 AGREEMENT_APPENDIX
 */
public enum DocumentType {
    PROJECT_PLAN, MARKET_RESEARCH, SPECIFICATIONS, QUALIFICATION_DOCUMENTS, CALL_FOR_TENDERS, ADDITIONAL_INFORMATION, CANDIDATES_NUMBER_LIMITATION_PROTOCOL,
    QUALIFICATIONS_EVALUATION_PROTOCOL, BIDDER_NEGOTIATION_PROTOCOL, OWNERSHIP_STRUCTURE, OBJECTION, TENDER, EVALUATION_COMITTEE_PROTOCOL,
    TENDERS_EVALUATION_PROTOCOL, BEST_TENDER_SELECTION_NOTICE, CONTRACTOR_AGREEMENT, AGREEMENT_AMENDMENT, BUYER_REPORT, BUYERS_GROUPING_AGREEMENT, AGREEMENT_APPENDIX
}