package com.twitchsnitch.importer.opentender.enums;

/**
 NPWP REASON	negotiated procedure without publication reason
 NO_VALID_OFFERS_IN_PRECEEDING_PROCUREMENT
 RESEARCH_PROCUREMENT
 TECHNICAL_EXCLUSIVITY
 ART_EXCLUSIVITY
 AUTHORSHIP_RIGHTS_EXCLUSIVITY
 EMERGENCY
 ADDITIONAL_WORK
 PROPOSAL_CONTEST_FOLLOW_UP
 COMMODITY_MARKET
 ADVANTAGEOUS_CONDITIONS
 FRAMEWORK_AGREEMENT
 OUTSIDE_DIRECTIVE
 */
public enum NPWPReason {
    NO_VALID_OFFERS_IN_PRECEEDING_PROCUREMENT, RESEARCH_PROCUREMENT, TECHNICAL_EXCLUSIVITY, ART_EXCLUSIVITY, AUTHORSHIP_RIGHTS_EXCLUSIVITY,
    EMERGENCY, ADDITIONAL_WORK, PROPOSAL_CONTEST_FOLLOW_UP, COMMODITY_MARKET, ADVANTAGEOUS_CONDITIONS, FRAMEWORK_AGREEMENT, OUTSIDE_DIRECTIVE
}